### ISSUE TITLE
Enviar QRCode para o navegado

### ISSUE THREAD

**Issue by roliveira3891** [edupoli/whatsapp-api#3]
Primeiro lugar: muito bom!

Agora me ajude em algo: como envio o qrcode para o navegado, para conectar? invés de deixar apenas no prompt?

abs,

**Comment by roliveira3891** [comment]
Resolvi. Obrigado!

**Comment by edupoli** [comment]
Desculpa a demora não tinha visto sua pergunta, que bom que conseguiu resolver 👍
